package edd2_proyecto_;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import  java.io.BufferedWriter ;
import  java.io.File ;
import  java.io.FileNotFoundException ;
import  java.io.FileWriter ;
import  java.io.IOException ;
import  java.text.ParseException ;
import  java.util.Scanner ;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Archivo = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        bt_Nuevo = new javax.swing.JButton();
        bt_Salvar = new javax.swing.JButton();
        bt_Cerrar = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        bt_Cargar = new javax.swing.JButton();
        jd_Campos = new javax.swing.JDialog();
        jb_BorrarCampos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jb_CrearCampo = new javax.swing.JButton();
        jb_ModificarCampos = new javax.swing.JButton();
        jb_ListarCampos = new javax.swing.JButton();
        jb_SalirdeCampos = new javax.swing.JButton();
        jd_Registros = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jb_SalirDeRegistros = new javax.swing.JButton();
        jd_indices = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jb_CrearIndice = new javax.swing.JButton();
        jb_ReIndexarArchivos = new javax.swing.JButton();
        jd_Estandarizacion = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jd_CrearCampo = new javax.swing.JDialog();
        jl_nameCampo = new javax.swing.JLabel();
        tf_NombredelCampo = new javax.swing.JTextField();
        jl_tipodevariable = new javax.swing.JLabel();
        jb_TerminarCreacionCampo = new javax.swing.JButton();
        rb_tip_string = new javax.swing.JRadioButton();
        rb_tip_integer = new javax.swing.JRadioButton();
        jl_longitud = new javax.swing.JLabel();
        tf_longitudelcampo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rb_key_si = new javax.swing.JRadioButton();
        rb_key_no = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jb_RegresarDeCrearCampo = new javax.swing.JButton();
        bg_TipoDeVariable = new javax.swing.ButtonGroup();
        bg_LlavePrimaria = new javax.swing.ButtonGroup();
        jd_ModificarCampo = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Campos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jb_RegresarDeCampos = new javax.swing.JButton();
        jb_CampoModificar = new javax.swing.JButton();
        jd_ListarCampos = new javax.swing.JDialog();
        jb_RegresarDeListarC = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_ListaDeCampos = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jd_EliminarCampos = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_EliminarCampos = new javax.swing.JTable();
        jb_RegresaDeEliminarCampos = new javax.swing.JButton();
        jb_EliminarCampoSelec = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jd_DatosDelCampo = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jd_nombre = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tf_nombreArchivo = new javax.swing.JTextField();
        jb_Archivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_Campos = new javax.swing.JButton();
        jb_Registros = new javax.swing.JButton();
        jb_Indices = new javax.swing.JButton();
        jb_Estandarizacion = new javax.swing.JButton();
        jb_Salir1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Archivo");

        bt_Nuevo.setText("Nuevo Archivo");
        bt_Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_NuevoMouseClicked(evt);
            }
        });

        bt_Salvar.setText("Salvar Archivo");
        bt_Salvar.setEnabled(false);
        bt_Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_SalvarMouseClicked(evt);
            }
        });

        bt_Cerrar.setText("Cerrar Archivo");
        bt_Cerrar.setEnabled(false);
        bt_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CerrarMouseClicked(evt);
            }
        });

        jButton10.setText("Regresar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        bt_Cargar.setText("Cargar Archivo");
        bt_Cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CargarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ArchivoLayout = new javax.swing.GroupLayout(jd_Archivo.getContentPane());
        jd_Archivo.getContentPane().setLayout(jd_ArchivoLayout);
        jd_ArchivoLayout.setHorizontalGroup(
            jd_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ArchivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(jd_ArchivoLayout.createSequentialGroup()
                .addGroup(jd_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ArchivoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jd_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jd_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_ArchivoLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jd_ArchivoLayout.setVerticalGroup(
            jd_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ArchivoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jb_BorrarCampos.setText("Borrar Campos");
        jb_BorrarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_BorrarCamposMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Campos");

        jb_CrearCampo.setText("Crear Campos");
        jb_CrearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearCampoMouseClicked(evt);
            }
        });

        jb_ModificarCampos.setText("Modificar Campos");
        jb_ModificarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ModificarCamposMouseClicked(evt);
            }
        });

        jb_ListarCampos.setText("Listar Campos");
        jb_ListarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ListarCamposMouseClicked(evt);
            }
        });

        jb_SalirdeCampos.setText("Salir");
        jb_SalirdeCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SalirdeCamposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CamposLayout = new javax.swing.GroupLayout(jd_Campos.getContentPane());
        jd_Campos.getContentPane().setLayout(jd_CamposLayout);
        jd_CamposLayout.setHorizontalGroup(
            jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CamposLayout.createSequentialGroup()
                .addGroup(jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CamposLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_CrearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_ModificarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_ListarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_BorrarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_CamposLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CamposLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jb_SalirdeCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jd_CamposLayout.setVerticalGroup(
            jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CamposLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ListarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_CrearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ModificarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_BorrarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_SalirdeCampos)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Registros");

        jButton15.setText("Introducir Registros");

        jButton16.setText("Modificar Registros");

        jButton17.setText("Buscar Registros");

        jButton18.setText("Borrar Registros");

        jButton19.setText("Listar Registros");

        jb_SalirDeRegistros.setText("Salir");
        jb_SalirDeRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SalirDeRegistrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_RegistrosLayout = new javax.swing.GroupLayout(jd_Registros.getContentPane());
        jd_Registros.getContentPane().setLayout(jd_RegistrosLayout);
        jd_RegistrosLayout.setHorizontalGroup(
            jd_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RegistrosLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_RegistrosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jd_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_SalirDeRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jd_RegistrosLayout.setVerticalGroup(
            jd_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RegistrosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jd_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_RegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jb_SalirDeRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Índices");

        jb_CrearIndice.setText("Crear Índices");

        jb_ReIndexarArchivos.setText("Re Indexar Archivos");

        javax.swing.GroupLayout jd_indicesLayout = new javax.swing.GroupLayout(jd_indices.getContentPane());
        jd_indices.getContentPane().setLayout(jd_indicesLayout);
        jd_indicesLayout.setHorizontalGroup(
            jd_indicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_indicesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jb_CrearIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jb_ReIndexarArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_indicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(139, 139, 139))
        );
        jd_indicesLayout.setVerticalGroup(
            jd_indicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_indicesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(jd_indicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_CrearIndice, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jb_ReIndexarArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Estandarización");

        jButton22.setText("Exportar Excel");

        jButton23.setText("Exportar XML con Schema");

        javax.swing.GroupLayout jd_EstandarizacionLayout = new javax.swing.GroupLayout(jd_Estandarizacion.getContentPane());
        jd_Estandarizacion.getContentPane().setLayout(jd_EstandarizacionLayout);
        jd_EstandarizacionLayout.setHorizontalGroup(
            jd_EstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EstandarizacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton23)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_EstandarizacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jd_EstandarizacionLayout.setVerticalGroup(
            jd_EstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EstandarizacionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jd_EstandarizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jl_nameCampo.setText("Nombre del campo:");

        jl_tipodevariable.setText("Tipo de variable:");

        jb_TerminarCreacionCampo.setText("Crear Campo");
        jb_TerminarCreacionCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_TerminarCreacionCampoMouseClicked(evt);
            }
        });

        bg_TipoDeVariable.add(rb_tip_string);
        rb_tip_string.setSelected(true);
        rb_tip_string.setText("String");

        bg_TipoDeVariable.add(rb_tip_integer);
        rb_tip_integer.setText("Integer");

        jl_longitud.setText("Longitud del campo:");

        jLabel7.setText("Es llave primaria?");

        bg_LlavePrimaria.add(rb_key_si);
        rb_key_si.setText("Si");

        bg_LlavePrimaria.add(rb_key_no);
        rb_key_no.setSelected(true);
        rb_key_no.setText("No");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("CREACIÓN DE CAMPO");

        jb_RegresarDeCrearCampo.setText("Regresar");
        jb_RegresarDeCrearCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RegresarDeCrearCampoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearCampoLayout = new javax.swing.GroupLayout(jd_CrearCampo.getContentPane());
        jd_CrearCampo.getContentPane().setLayout(jd_CrearCampoLayout);
        jd_CrearCampoLayout.setHorizontalGroup(
            jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_longitud)
                    .addComponent(jl_nameCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                        .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_longitudelcampo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_NombredelCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                                .addComponent(rb_key_si)
                                .addGap(10, 10, 10)
                                .addComponent(rb_key_no))
                            .addComponent(jLabel7))
                        .addGap(78, 78, 78))
                    .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jb_TerminarCreacionCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_RegresarDeCrearCampo)
                .addGap(109, 109, 109))
            .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_tipodevariable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_tip_string)
                .addGap(18, 18, 18)
                .addComponent(rb_tip_integer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_CrearCampoLayout.setVerticalGroup(
            jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jl_nameCampo)
                            .addComponent(tf_NombredelCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_key_si)
                            .addComponent(rb_key_no)))
                    .addGroup(jd_CrearCampoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(127, 127, 127)
                        .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_longitud)
                            .addComponent(tf_longitudelcampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tipodevariable)
                    .addComponent(rb_tip_string)
                    .addComponent(rb_tip_integer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jd_CrearCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_TerminarCreacionCampo)
                    .addComponent(jb_RegresarDeCrearCampo))
                .addGap(21, 21, 21))
        );

        jt_Campos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Longitud", "Tipo", "Es Llave Primaria[s/n]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_Campos);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("CAMPOS");

        jb_RegresarDeCampos.setText("Regresar");
        jb_RegresarDeCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RegresarDeCamposMouseClicked(evt);
            }
        });

        jb_CampoModificar.setText("Modificar");
        jb_CampoModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CampoModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ModificarCampoLayout = new javax.swing.GroupLayout(jd_ModificarCampo.getContentPane());
        jd_ModificarCampo.getContentPane().setLayout(jd_ModificarCampoLayout);
        jd_ModificarCampoLayout.setHorizontalGroup(
            jd_ModificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarCampoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(jd_ModificarCampoLayout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarCampoLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jb_CampoModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_RegresarDeCampos)
                .addGap(88, 88, 88))
        );
        jd_ModificarCampoLayout.setVerticalGroup(
            jd_ModificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModificarCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jd_ModificarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_RegresarDeCampos)
                    .addComponent(jb_CampoModificar))
                .addContainerGap())
        );

        jb_RegresarDeListarC.setText("Regresar");
        jb_RegresarDeListarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RegresarDeListarCMouseClicked(evt);
            }
        });

        jt_ListaDeCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Longitud", "Tipo", "Es llave Primaria[s/n]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_ListaDeCampos);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Campos Creados");

        javax.swing.GroupLayout jd_ListarCamposLayout = new javax.swing.GroupLayout(jd_ListarCampos.getContentPane());
        jd_ListarCampos.getContentPane().setLayout(jd_ListarCamposLayout);
        jd_ListarCamposLayout.setHorizontalGroup(
            jd_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarCamposLayout.createSequentialGroup()
                .addComponent(jb_RegresarDeListarC)
                .addGap(88, 88, 88)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ListarCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jd_ListarCamposLayout.setVerticalGroup(
            jd_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarCamposLayout.createSequentialGroup()
                .addGroup(jd_ListarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_RegresarDeListarC)
                    .addGroup(jd_ListarCamposLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Campos Creados");

        jt_EliminarCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Longitud", "Tipo", "Es Llave Primaria[s/n]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jt_EliminarCampos);

        jb_RegresaDeEliminarCampos.setText("Regresar");
        jb_RegresaDeEliminarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_RegresaDeEliminarCamposMouseClicked(evt);
            }
        });

        jb_EliminarCampoSelec.setText("Eliminar");
        jb_EliminarCampoSelec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarCampoSelecMouseClicked(evt);
            }
        });

        jLabel12.setText("Seleccion que campo quiere eliminar");

        javax.swing.GroupLayout jd_EliminarCamposLayout = new javax.swing.GroupLayout(jd_EliminarCampos.getContentPane());
        jd_EliminarCampos.getContentPane().setLayout(jd_EliminarCamposLayout);
        jd_EliminarCamposLayout.setHorizontalGroup(
            jd_EliminarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarCamposLayout.createSequentialGroup()
                .addComponent(jb_RegresaDeEliminarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_EliminarCampoSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_EliminarCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(201, 201, 201))
            .addGroup(jd_EliminarCamposLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jd_EliminarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jd_EliminarCamposLayout.setVerticalGroup(
            jd_EliminarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EliminarCamposLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_EliminarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_EliminarCampoSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_RegresaDeEliminarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Datos del Campo");

        javax.swing.GroupLayout jd_DatosDelCampoLayout = new javax.swing.GroupLayout(jd_DatosDelCampo.getContentPane());
        jd_DatosDelCampo.getContentPane().setLayout(jd_DatosDelCampoLayout);
        jd_DatosDelCampoLayout.setHorizontalGroup(
            jd_DatosDelCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DatosDelCampoLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel13)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jd_DatosDelCampoLayout.setVerticalGroup(
            jd_DatosDelCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DatosDelCampoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel14.setText("Nombre del Archivo");

        javax.swing.GroupLayout jd_nombreLayout = new javax.swing.GroupLayout(jd_nombre.getContentPane());
        jd_nombre.getContentPane().setLayout(jd_nombreLayout);
        jd_nombreLayout.setHorizontalGroup(
            jd_nombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nombreLayout.createSequentialGroup()
                .addGroup(jd_nombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_nombreLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButton1))
                    .addGroup(jd_nombreLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addComponent(tf_nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jd_nombreLayout.setVerticalGroup(
            jd_nombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nombreLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jd_nombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_nombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Standard File Manager");
        setName("Standard File Manager"); // NOI18N

        jb_Archivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_Archivo.setText("Archivo");
        jb_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ArchivoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Standard File Manager");
        jLabel1.setName("Standard File Manager"); // NOI18N

        jb_Campos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_Campos.setText("Campos");
        jb_Campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CamposActionPerformed(evt);
            }
        });

        jb_Registros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_Registros.setText("Registros");

        jb_Indices.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_Indices.setText("Índices");
        jb_Indices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_IndicesActionPerformed(evt);
            }
        });

        jb_Estandarizacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_Estandarizacion.setText("Estandarización");
        jb_Estandarizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EstandarizacionActionPerformed(evt);
            }
        });

        jb_Salir1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_Salir1.setText("Salir");
        jb_Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Salir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_Archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Estandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_Indices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_Campos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_Indices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Registros, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_Estandarizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Salir1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jb_Salir1ActionPerformed

    private void jb_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ArchivoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jd_Archivo.pack();
        jd_Archivo.setModal(true);
        jd_Archivo.setLocationRelativeTo(this);
        jd_Archivo.setVisible(true);
    }//GEN-LAST:event_jb_ArchivoActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jd_Archivo.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jb_CamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CamposActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jd_Campos.pack();
        jd_Campos.setModal(true);
        jd_Campos.setLocationRelativeTo(this);
        jd_Campos.setVisible(true);
    }//GEN-LAST:event_jb_CamposActionPerformed

    private void jb_IndicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_IndicesActionPerformed
        // TODO add your handling code here:
        jd_indices.pack();
        jd_indices.setModal(true);
        jd_indices.setLocationRelativeTo(this);
        jd_indices.setVisible(true);
    }//GEN-LAST:event_jb_IndicesActionPerformed

    private void jb_EstandarizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EstandarizacionActionPerformed
        // TODO add your handling code here:
        jd_Estandarizacion.pack();
        jd_Estandarizacion.setModal(true);
        jd_Estandarizacion.setLocationRelativeTo(this);
        jd_Estandarizacion.setVisible(true);
    }//GEN-LAST:event_jb_EstandarizacionActionPerformed

    private void jb_CrearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearCampoMouseClicked
        jd_CrearCampo.pack();
        jd_CrearCampo.setModal(true);
        jd_CrearCampo.setLocationRelativeTo(this);
        jd_CrearCampo.setVisible(true);
    }//GEN-LAST:event_jb_CrearCampoMouseClicked

    private void jb_SalirdeCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SalirdeCamposMouseClicked
        jd_Campos.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jb_SalirdeCamposMouseClicked

    private void jb_SalirDeRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SalirDeRegistrosMouseClicked
        jd_Registros.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jb_SalirDeRegistrosMouseClicked

    private void jb_TerminarCreacionCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_TerminarCreacionCampoMouseClicked
       String nombre = tf_NombredelCampo.getText();
       int longitud = Integer.parseInt(tf_longitudelcampo.getText()) ;
       boolean key;
       
       if(rb_key_no.isSelected()){
           key = false;
       }else{
           key = true;
       }
          
       if(rb_tip_integer.isSelected()){
           campos.add(new Campo(nombre, "int", key, longitud));
           
       }else{
           campos.add(new Campo(nombre, "String", key, longitud));
       }
       
       tf_NombredelCampo.setText("");
       tf_longitudelcampo.setText("");
       rb_key_no.setSelected(true);
       rb_tip_string.setSelected(true);
    }//GEN-LAST:event_jb_TerminarCreacionCampoMouseClicked


    private void jb_ModificarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ModificarCamposMouseClicked
        DefaultTableModel model = (DefaultTableModel)jt_Campos.getModel();
        
        String llave_o_no;
        
        for (int i = 0; i < campos.size(); i++) {
            if(campos.get(i).isLlave_primaria())
                llave_o_no = "S";
            else
                llave_o_no = "N";
            Object[] newRow = {campos.get(i).getNombre(), campos.get(i).getLongitud(),campos.get(i).getTipo(),llave_o_no
            
            };
            model.addRow(newRow);
        }
        
        jt_Campos.setModel(model);
        
        
        jd_Campos.setVisible(false);
        jd_ModificarCampo.pack();
        jd_ModificarCampo.setModal(true);
        jd_ModificarCampo.setLocationRelativeTo(jd_Campos);
        jd_ModificarCampo.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jb_ModificarCamposMouseClicked

    private void jb_RegresarDeCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RegresarDeCamposMouseClicked
        jt_Campos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Longitud", "Tipo", "Es Llave Primaria[s/n]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jd_ModificarCampo.dispose();
        jd_Campos.setVisible(true);
    }//GEN-LAST:event_jb_RegresarDeCamposMouseClicked

    private void jb_CampoModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CampoModificarMouseClicked
        DefaultTableModel model = (DefaultTableModel) jt_Campos.getModel();
        if(jt_Campos.getSelectedRow() >= 0){
            int opcion = Integer.parseInt(JOptionPane.showInputDialog("1.Modificar Nombre del Campo\n"
                    + "2.Modificar Longitud del Campo\n"
                    + "3.Modificar Tipo de Dato\n"
                    + "4.Cambiar Si es llave Primaria o No"));
            
            if(opcion == 1){
                String newName = JOptionPane.showInputDialog("Ingrese el Nuevo Nombre del Campo:");
                jt_Campos.setValueAt(newName, jt_Campos.getSelectedRow(), 0);
                campos.get(jt_Campos.getSelectedRow()).setNombre(newName);
            }
            
            if(opcion == 2){
                int newLongitud = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la Nueva Longitud del Campo:"));
                jt_Campos.setValueAt(newLongitud, jt_Campos.getSelectedRow(), 1);
                campos.get(jt_Campos.getSelectedRow()).setLongitud(newLongitud);
            }
            
            if(opcion == 3){
                String newType = JOptionPane.showInputDialog("Ingrese el Nuevo Tipo del Campo:");
                newType.toUpperCase();
                if(newType.equals("INTEGER") || !newType.equals("STRING")){
                    JOptionPane.showMessageDialog(jd_ModificarCampo, "Ese Tipo de Datos no es Soportado");
                }else{
                    jt_Campos.setValueAt(newType, jt_Campos.getSelectedRow(), 2);
                    campos.get(jt_Campos.getSelectedRow()).setTipo(newType);
                }
            }
            
            if(opcion == 4){
                String newLLave = JOptionPane.showInputDialog("Ingrese S si la llave es Primaria y N si no lo es");
                newLLave.toUpperCase();
                if(newLLave.equals("S")){
                    jt_Campos.setValueAt(newLLave, jt_Campos.getSelectedRow(), 3);
                    campos.get(jt_Campos.getSelectedRow()).setLlave_primaria(true);
                }
                if(newLLave.equals("N")){
                    jt_Campos.setValueAt(newLLave, jt_Campos.getSelectedRow(), 3);
                    campos.get(jt_Campos.getSelectedRow()).setLlave_primaria(false);
                }
                
                
            }
            
        }else{
            JOptionPane.showMessageDialog(jd_ModificarCampo, "No ha Seleccionado Un Elemento");
        }
    }//GEN-LAST:event_jb_CampoModificarMouseClicked

    private void jb_RegresarDeCrearCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RegresarDeCrearCampoMouseClicked
        jd_CrearCampo.dispose();
        jd_Campos.setVisible(true);
    }//GEN-LAST:event_jb_RegresarDeCrearCampoMouseClicked

    private void jb_ListarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ListarCamposMouseClicked
        DefaultTableModel model = (DefaultTableModel)jt_ListaDeCampos.getModel();
        String llave_o_no;
        for (int i = 0; i < campos.size(); i++) {
            if(campos.get(i).isLlave_primaria())
                llave_o_no = "S";
            else
                llave_o_no = "N";

            Object[] newRow = {campos.get(i).getNombre(), campos.get(i).getLongitud(),campos.get(i).getTipo(),llave_o_no
            
            };
            model.addRow(newRow);
        }
        
        jt_ListaDeCampos.setModel(model);
        
        jd_Campos.setVisible(false);
        jd_ListarCampos.pack();
        jd_ListarCampos.setModal(true);
        jd_ListarCampos.setLocationRelativeTo(this);
        jd_ListarCampos.setVisible(true);
    }//GEN-LAST:event_jb_ListarCamposMouseClicked

    private void jb_RegresarDeListarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RegresarDeListarCMouseClicked
        jt_ListaDeCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Longitud", "Tipo", "Es Llave Primaria[s/n]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jd_ListarCampos.dispose();
        jd_Campos.setVisible(true);
    }//GEN-LAST:event_jb_RegresarDeListarCMouseClicked

    private void jb_BorrarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_BorrarCamposMouseClicked
        DefaultTableModel model = (DefaultTableModel)jt_EliminarCampos.getModel();
        jt_EliminarCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Longitud", "Tipo", "Es Llave Primaria[s/n]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        for (int i = 0; i < campos.size(); i++) {
            String type = campos.get(i).getTipo();
            Object[] newRow = {campos.get(i).getNombre(), campos.get(i).getLongitud(),campos.get(i).getTipo(),type
            
            };
            model.addRow(newRow);
        }
        
        jt_EliminarCampos.setModel(model);
        
        jd_Campos.setVisible(false);
        jd_EliminarCampos.pack();
        jd_EliminarCampos.setModal(true);
        jd_EliminarCampos.setLocationRelativeTo(this);
        jd_EliminarCampos.setVisible(true);
    }//GEN-LAST:event_jb_BorrarCamposMouseClicked

    private void jb_EliminarCampoSelecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarCampoSelecMouseClicked
        int selected = jt_EliminarCampos.getSelectedRow();
        campos.remove(selected);
        
        DefaultTableModel model = (DefaultTableModel)jt_EliminarCampos.getModel();
        jt_EliminarCampos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Longitud", "Tipo", "Es Llave Primaria[s/n]"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        for (int i = 0; i < campos.size(); i++) {
            String type = campos.get(i).getTipo();
            Object[] newRow = {campos.get(i).getNombre(), campos.get(i).getLongitud(),campos.get(i).getTipo(),type
            
            };
            model.addRow(newRow);
        }
        
        jt_EliminarCampos.setModel(model);
    }//GEN-LAST:event_jb_EliminarCampoSelecMouseClicked

    private void jb_RegresaDeEliminarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_RegresaDeEliminarCamposMouseClicked
        jd_EliminarCampos.dispose();
        jd_Campos.setVisible(true);
    }//GEN-LAST:event_jb_RegresaDeEliminarCamposMouseClicked

    private void jb_TerminarCreacionCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_TerminarCreacionCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_TerminarCreacionCampoActionPerformed


    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jd_DatosDelCampo.dispose();
        jd_ModificarCampo.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jb_InfoAceptarCambiosDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_InfoAceptarCambiosDatosMouseClicked
  /*      DefaultTableModel model = (DefaultTableModel) jt_Campos.getModel();
        int indice = jt_Campos.getSelectedRow();
        int cont = 0;
        
        String newNombre, newTipo;
        int newLongitud;
        
       newNombre = tf_InfoNombreCampo.getText();
        newLongitud = (int) js_InfoLongitudCampo.getValue();
        
        if(rb_InfoStringCampo.isSelected())
            newTipo = "String";
        else
            newTipo = "int";
        
        
        if(!newNombre.equals(campos.get(indice).getNombre())){
            campos.get(indice).setNombre(newNombre);
            jt_Campos.setValueAt(newNombre, indice, 0);
            cont++;
        }
            
        if(!newTipo.equals(campos.get(indice).getTipo())){
            campos.get(indice).setTipo(newTipo);
            jt_Campos.setValueAt(newTipo, indice, 2);
            cont++;
            
        }
        
        if(newLongitud != campos.get(indice).getLongitud()){
            campos.get(indice).setLongitud(newLongitud);
            jt_Campos.setValueAt(newLongitud, indice, 1);
            cont++;
        }
        
        
        if(cont > 0)
            JOptionPane.showMessageDialog(jd_DatosDelCampo, "Datos Modificados Correctamente");
        else
            JOptionPane.showMessageDialog(jd_DatosDelCampo, "No se ha Modificado Ningún Dato");
            
        jd_DatosDelCampo.dispose();
        jd_ModificarCampo.setVisible(true);
        */
    }//GEN-LAST:event_jb_InfoAceptarCambiosDatosMouseClicked

    private void bt_NuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_NuevoMouseClicked
        // TODO add your handling code here:
        jd_nombre.pack();
        jd_nombre.setModal(true);
        jd_nombre.setLocationRelativeTo(this);
        jd_nombre.setVisible(true);
    }//GEN-LAST:event_bt_NuevoMouseClicked

    private void bt_SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_SalvarMouseClicked
        // TODO add your handling code here:
        currentFile.setlistaCampo(campos);
        currentFile.escribirArchivo();
        JOptionPane.showMessageDialog(this, "El archivo se guardo exitosamente!");
        
    }//GEN-LAST:event_bt_SalvarMouseClicked

    private void bt_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CerrarMouseClicked
        // TODO add your handling code here:
        currentFile = null;
        campos.clear();
        bt_Cerrar.setEnabled(false);
        bt_Salvar.setEnabled(false);
        bt_Nuevo.setEnabled(true);
        bt_Cargar.setEnabled(true);
    }//GEN-LAST:event_bt_CerrarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        if(tf_nombreArchivo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un nombre para el archivo");
        }
        else
        {
            String nombre = tf_nombreArchivo.getText();
            try {
                currentFile = new Archivo("./" + nombre + ".aajs");
            } catch (IOException ex) {
            }
            bt_Cerrar.setEnabled(true);
            bt_Salvar.setEnabled(true);
            bt_Nuevo.setEnabled(false);
            bt_Cargar.setEnabled(false);
            JOptionPane.showMessageDialog(this, "El Archivo se creo exitosamente");
            jd_nombre.dispose();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_CargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CargarMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION)
        {
            File file = fc.getSelectedFile();
            currentFile = new Archivo(file);
            try {
                currentFile.cargarArchivo();
            } catch (IOException ex) {
                Logger.getLogger(Ventana_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            campos = currentFile.getListaCampo();
            bt_Cerrar.setEnabled(true);
            bt_Salvar.setEnabled(true);
            bt_Nuevo.setEnabled(false);
            bt_Cargar.setEnabled(false);
        }
        
    }//GEN-LAST:event_bt_CargarMouseClicked



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_LlavePrimaria;
    private javax.swing.ButtonGroup bg_TipoDeVariable;
    private javax.swing.JButton bt_Cargar;
    private javax.swing.JButton bt_Cerrar;
    private javax.swing.JButton bt_Nuevo;
    private javax.swing.JButton bt_Salvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_Archivo;
    private javax.swing.JButton jb_BorrarCampos;
    private javax.swing.JButton jb_CampoModificar;
    private javax.swing.JButton jb_Campos;
    private javax.swing.JButton jb_CrearCampo;
    private javax.swing.JButton jb_CrearIndice;
    private javax.swing.JButton jb_EliminarCampoSelec;
    private javax.swing.JButton jb_Estandarizacion;
    private javax.swing.JButton jb_Indices;
    private javax.swing.JButton jb_ListarCampos;
    private javax.swing.JButton jb_ModificarCampos;
    private javax.swing.JButton jb_ReIndexarArchivos;
    private javax.swing.JButton jb_Registros;
    private javax.swing.JButton jb_RegresaDeEliminarCampos;
    private javax.swing.JButton jb_RegresarDeCampos;
    private javax.swing.JButton jb_RegresarDeCrearCampo;
    private javax.swing.JButton jb_RegresarDeListarC;
    private javax.swing.JButton jb_Salir1;
    private javax.swing.JButton jb_SalirDeRegistros;
    private javax.swing.JButton jb_SalirdeCampos;
    private javax.swing.JButton jb_TerminarCreacionCampo;
    private javax.swing.JDialog jd_Archivo;
    private javax.swing.JDialog jd_Campos;
    private javax.swing.JDialog jd_CrearCampo;
    private javax.swing.JDialog jd_DatosDelCampo;
    private javax.swing.JDialog jd_EliminarCampos;
    private javax.swing.JDialog jd_Estandarizacion;
    private javax.swing.JDialog jd_ListarCampos;
    private javax.swing.JDialog jd_ModificarCampo;
    private javax.swing.JDialog jd_Registros;
    private javax.swing.JDialog jd_indices;
    private javax.swing.JDialog jd_nombre;
    private javax.swing.JLabel jl_longitud;
    private javax.swing.JLabel jl_nameCampo;
    private javax.swing.JLabel jl_tipodevariable;
    private javax.swing.JTable jt_Campos;
    private javax.swing.JTable jt_EliminarCampos;
    private javax.swing.JTable jt_ListaDeCampos;
    private javax.swing.JRadioButton rb_key_no;
    private javax.swing.JRadioButton rb_key_si;
    private javax.swing.JRadioButton rb_tip_integer;
    private javax.swing.JRadioButton rb_tip_string;
    private javax.swing.JTextField tf_NombredelCampo;
    private javax.swing.JTextField tf_longitudelcampo;
    private javax.swing.JTextField tf_nombreArchivo;
    // End of variables declaration//GEN-END:variables
    ArrayList<Campo> campos = new ArrayList();
    Archivo currentFile;
}
